version: '3'
services:
    rskj:
        container_name: rsk-node
        image: rsksmart/rskj:IRIS-3
        ports:
            - '127.0.0.1:4444:4444'
            - '127.0.0.1:4445:4445'
        networks:
            - 'rif-relay-testing'
        volumes:
            - logback.xml:/usr/local/rskj/logback.xml
            - node.conf:/usr/local/rskj/node.conf

networks:
    rif-relay-testing:
        external: true
