version: '3'
services:
    rskj:
        container_name: rsk-node
        image: rsksmart/rskj:IRIS-3
        command: java -Drsk.conf.file=./node.conf -Dlogback.configurationFile=./logback.xml -cp ./rsk.jar co.rsk.Start --regtest
        ports:
            - '127.0.0.1:4444:4444'
            - '127.0.0.1:4445:4445'
        networks:
            - 'rif-relay-testing'
        volumes:
            - logback.xml:/home/rsk/logback.xml
            - node.conf:/home/rsk/node.conf
        entrypoint: ""

networks:
    rif-relay-testing:
        external: true
