version: '3'
services:
    rskj:
        container_name: rsk-node
        image: rsksmart/rskj:IRIS-3
        ports:
            - '4444:4444'
            - '4445:4445'
        networks:
            - 'rif-relay-testing'
        volumes:
            - ./logback.xml:/etc/rsk/logback.xml
            - ./node.conf:/etc/rsk/node.conf

networks:
    rif-relay-testing:
        external: true
